spring.application.name=dproject-portfolio-api
server.port=8081
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${PORTFOLIO_DB_URL:jdbc:postgresql://localhost:${PORTFOLIO_DB_PORT:5433}/${PORTFOLIO_DB_NAME:portfolio_db}}
spring.datasource.username=${PORTFOLIO_DB_USERNAME:portfolio_user}
spring.datasource.password=${PORTFOLIO_DB_PASSWORD:portfolio_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=portfolio

spring.flyway.enabled=true
spring.flyway.validate-migration-naming=true

app.jwt.secret=${PORTFOLIO_JWT_SECRET:Q2hhbmdlVGhpc0RlbW9LZXlCZWZvcmVEZXBsb3ltZW50MTIzNDU2Nzg5MA==}
app.jwt.issuer=dproject-portfolio-api
app.jwt.expiration=PT1H

app.external-member.base-url=${PORTFOLIO_MEMBER_API_URL:http://localhost:${PORTFOLIO_MEMBER_MOCK_PORT:8083}}
