spring.application.name=dproject-portfolio-api
server.port=8081
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${PORTFOLIO_DB_URL:jdbc:postgresql://localhost:${PORTFOLIO_DB_PORT:5433}/${PORTFOLIO_DB_NAME:portfolio_db}}
spring.datasource.username=${PORTFOLIO_DB_USERNAME:portfolio_user}
spring.datasource.password=${PORTFOLIO_DB_PASSWORD:portfolio_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=portfolio

spring.flyway.enabled=true
spring.flyway.validate-migration-naming=true
